spring:
  datasource:
    url: "jdbc:h2:mem:dev"
    username: sa
    password: 123
  h2:
    console:
      enabled: true
      path: /h2console/
    settings:
      web-allow-others: true
  sentry:
    dsn: https://5694e60e9d608b9372b1ede62b68bf54@o4506455882072064.ingest.sentry.io/4506455893409792
    # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
    # We recommend adjusting this value in production.
    traces-sample-rate: 1.0
    environment: production